# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_message_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='slug',
        ),
    ]
